### ISSUE TITLE
Sanitizer problem with some abstracts

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [inspirehep/inspirehep-search-js#6]
There is an issue with the sanitizer in the abstract of some records. 
<img width="729" alt="screen shot 2016-03-22 at 13 39 15" src="https://cloud.githubusercontent.com/assets/7301890/13951875/ad635f52-f033-11e5-858b-4dde1babe94d.png">

**Comment by ioannistsanaktsidis** [comment]
cc @kaplun @jmartinm .

**Comment by kaplun** [comment]
Hi @ioannistsanaktsidis I don't know (yet) what the `sanitizer` is, but is it possible that indeed the title is not valid? (e.g. has broken HTML in it, or broken LaTeX?)

**Comment by kaplun** [comment]
What record is this?

**Comment by ioannistsanaktsidis** [comment]
Hey @kaplun , just saw the problem while I was messing creating some directives. I can check a bit more. I just created the issue so as not to forget it ;)
